import torch
import torch.nn as nn
from torch import Tensor
import math

class APE(nn.Module):
    """
    Absolute Position Encoding using random sinusoidal features.

    This module maps spatial coordinates to a high-dimensional embedding vector
    using a fixed, randomly initialized set of sinusoidal basis functions. This is a
    common technique for representing positions in transformer-like models, often
    referred to as Random Fourier Features.

    The embedding is generated by computing `cos` and `sin` of the dot product
    between input positions and a set of random frequency vectors.

    Args:
        embed_dim (int): The total dimension of the output embedding. Must be an even number.
        freq_sigma (float): Standard deviation for sampling the initial random frequencies.
                           This controls the "wavelengths" of the positional signals.
        spatial_dims (int): The number of spatial dimensions of the input positions
                            (e.g., 3 for x, y, z coordinates).
        learned_freqs (bool): If True, the frequencies become learnable parameters instead
                              of a fixed buffer.
    """
    def __init__(
        self,
        embed_dim: int,
        freq_sigma: float,
        spatial_dims: int = 3,
        learned_freqs: bool = False,
    ):
        super().__init__()

        if embed_dim % 2 != 0:
            raise ValueError(f"embed_dim must be an even number, but got {embed_dim}.")

        self.embed_dim = embed_dim
        self.freq_sigma = freq_sigma
        self.spatial_dims = spatial_dims
        self.num_frequencies = self.embed_dim // 2

        # --- Frequency Initialization ---
        # Frequencies are drawn from a Gaussian distribution and scaled by sigma.
        # Shape: [spatial_dims, num_frequencies]
        freqs = torch.randn(self.spatial_dims, self.num_frequencies) * self.freq_sigma

        if learned_freqs:
            self.register_parameter("freqs", nn.Parameter(freqs))
        else:
            self.register_buffer("freqs", freqs)

    def forward(self, pos: Tensor) -> Tensor:
        """
        Compute the sinusoidal position embeddings for the given coordinates.

        Args:
            pos (Tensor): Position tensor of shape (..., spatial_dims). The leading
                          dimensions '...' can be anything (e.g., batch_size, num_atoms).

        Returns:
            Tensor: The calculated position embedding of shape (..., embed_dim).
        """
        # 1. --- Project positions onto frequency vectors ---
        # This computes the dot product between each position vector and each frequency vector.
        # pos shape: (..., d) | freqs shape: (d, f) -> angles shape: (..., f)
        # where d = spatial_dims and f = num_frequencies.
        angles = torch.einsum('...d,df->...f', pos, self.freqs)

        # 2. --- Compute sinusoidal features ---
        # The embedding is formed by concatenating the cosine and sine of the angles.
        # cos_angles shape: (..., f) | sin_angles shape: (..., f)
        cos_angles = torch.cos(angles)
        sin_angles = torch.sin(angles)

        # embedding shape: (..., 2*f) which is (..., embed_dim)
        embedding = torch.cat([cos_angles, sin_angles], dim=-1)

        return embedding